'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _component = require('../common/component');

var _component2 = _interopRequireDefault(_component);

var _classnames = require('classnames');

var _classnames2 = _interopRequireDefault(_classnames);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; } /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @ngdoc directive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @name radiobox.directive:bpRadioboxGroup
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @author chuxin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @restrict E
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @description
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 对radiobox的二次包装 提供`list`指令
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 包含的状态有
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * - enable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * - disabled
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * - checked
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @param {Boolean}         disabled        - binding symbol is `<`, 禁用状态,默认 `false`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @param {Boolean}         inline          - binding symbol is `<`, 是否横向展示,默认 `false`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @param {String}          model           - binding symbol is `=?model`, 绑定在`radioBoxGroup上`的`model`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @param {Array.<Object>}  list            - binding symbol is `=?list`, 数据源, `controller`提供的数组用于遍历展示`radio`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @example
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <bp-radio-group list="vm.groupDataList" model="vm.model"></bp-radio-group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.model = "这个杀手不太冷";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.groupDataList = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {label: '沉默的羔羊', value: '沉默的羔羊'},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {label: '这个杀手不太冷',value:'这个杀手不太冷'},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {label: '指环王',value:'指环王',complex:{author:'xxx',age:45,sex:'不详'}},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {label: '速度与激情',value:"速度与激情"},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {label: '魔兽世界', value:"魔兽世界",disabled: true},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {label: 'X战警',value:"X战警"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                更多例子的[传送门](https://ffan-fe.github.io/Anaheim/#/radiobox)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */

'use strict';

/**
 * RadioGroup component
 *
 * @export
 * @class RadioGroup
 * @extends {Component}
 */

var RadioboxGroup = function (_Component) {
  _inherits(RadioboxGroup, _Component);

  function RadioboxGroup() {
    _classCallCheck(this, RadioboxGroup);

    return _possibleConstructorReturn(this, (RadioboxGroup.__proto__ || Object.getPrototypeOf(RadioboxGroup)).apply(this, arguments));
  }

  _createClass(RadioboxGroup, [{
    key: '_initDefaultValue',


    /**
     * @override
     */
    value: function _initDefaultValue() {
      this.list = this.list && angular.isArray(this.list) ? this.list : [];
    }
  }, {
    key: '_createClassName',
    value: function _createClassName() {}
  }, {
    key: '_launch',
    value: function _launch() {}
  }]);

  return RadioboxGroup;
}(_component2.default);

exports.default = RadioboxGroup;